export const userTypes = {
    SET_USERNAME_LOGIN: 'SET_USERNAME_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    FORGOT_USERNAME_FAIL: 'FORGOT_USERNAME_FAIL',
    FORGOT_USERNAME_SUCCESS: 'FORGOT_USERNAME_SUCCESS',
    SET_USERNAME_FORGOTPASSWORD: 'SET_USERNAME_FORGOTPASSWORD',
    RESET_FORGOT_PASSWORD: 'RESET_FORGOT_PASSWORD',
    VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
    VERIFY_OTP_FAIL: 'VERIFY_OTP_FAIL',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAIL: 'FORGOT_PASSWORD_FAIL',
    RESET_IS_LOGIN: 'RESET_IS_LOGIN'
}

export const homeTypes = {
    SET_CATEGORY_ITEM: 'SET_CATEGORY_ITEM',
    SET_PRODUCER: "SET_PRODUCER",
    SET_PAGE: 'SET_PAGE',
    SET_ITEM: 'SET_ITEM',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
    SET_SORT_TYPE: 'SET_SORT_TYPE',
    SET_RANGE: 'SET_RANGE',
    SET_NAME_TITLE_ITEM: 'SET_NAME_TITLE_ITEM',
    RESET_ITEM: 'RESET_ITEM',
    SET_BRANCH_SEARCH_ITEM:'SET_BRANCH_SEARCH_ITEM', 
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
    SET_SHOP: 'SET_SHOP',
    SET_ID_BRANCH: 'SET_ID_BRANCH',
}

export const productTypes = {
    SET_PRODUCT_DETAIL: 'SET_PRODUCT_DETAIL',
    SET_NAME_CATEGORY: 'SET_NAME_CATEGORY',
    SET_NAME_PRODUCER: 'SET_NAME_PRODUCER',
    SET_ITEM_RELATED: 'SET_ITEM_RELATED',
    SET_COMMENT: 'SET_COMMENT',
    SET_NAME_SHOP: 'SET_NAME_SHOP',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
}
export const shopTypes = {
    SET_SHOP_DETAIL: 'SET_SHOP_DETAIL',
}
export const profileTypes = {
    SET_AUTH_LOGIN_SUCCESS: 'SET_AUTH_LOGIN_SUCCESS',
    SET_AUTH_LOGIN_FAIL: 'SET_AUTH_LOGIN_FAIL',

    UPDATE_INFOR_USER_SUCCESS: 'UPDATE_INFOR_USER_SUCCESS',
    UPDATE_INFOR_USER_FAIL: 'UPDATE_INFOR_USER_FAIL',
    RESET_PROFILE: 'RESET_PROFILE',
}
export const sortTypes =  {
    SORT_DAY_INCREASED: 'SORT_DAY_INCREASED',
    SORT_DAY_DECREASED: 'SORT_DAY_DECREASED',
    SORT_VIEWS_INCREASED: 'SORT_VIEWS_INCREASED',
    SORT_VIEWS_DECREASED: 'SORT_VIEWS_DECREASED',
    SORT_SALES_INCREASED: 'SORT_SALES_INCREASED',
    SORT_SALES_DECREASED: 'SORT_SALES_DECREASED',
    SORT_PRICE_INCREASED: 'SORT_PRICE_INCREASED',
    SORT_PRICE_DECREASED: 'SORT_PRICE_DECREASED',

}
export const cartTypes = {
    SET_CART: 'SET_CART',
    SET_CITY: 'SET_CITY',
    SET_DICTRICT: 'SET_DISTRICT',
    SET_WARD: 'SET_WARD',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAIL: 'PAYMENT_FAIL',
    RESET_PAYMENT: 'RESET_PAYMENT'
}
export const purchaseHistoryTypes = {
    SET_PURCHASED_HISTORY: 'SET_PURCHASED_HISTORY',
    
}