export const itemTypes = {
    SET_PAGE: 'SET_PAGE',
    SET_ITEM: 'SET_ITEM',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
    SET_CATEGORY_ITEM: 'SET_CATEGORY_ITEM',
    SET_PRODUCER: 'SET_PRODUCER',
    SET_SHOP: 'SET_SHOP',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAIL: 'ADD_CATEGORY_FAIL',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAIL: 'UPDATE_CATEGORY_FAIL',
    RESET_CATEGORY: 'RESET_CATEGORY',
    ADD_SHOP_SUCCESS: 'ADD_SHOP_SUCCESS',
    ADD_SHOP_FAIL: 'ADD_SHOP_FAIL',
    UPDATE_SHOP_SUCCESS: 'UPDATE_SHOP_SUCCESS',
    UPDATE_SHOP_FAIL: 'UPDATE_SHOP_FAIL',
    RESET_SHOP: 'RESET_SHOP',
    ADD_PRODUCER_SUCCESS: 'ADD_PRODUCER_SUCCESS',
    ADD_PRODUCER_FAIL: 'ADD_PRODUCER_FAIL',
    UPDATE_PRODUCER_SUCCESS: 'UPDATE_PRODUCER_SUCCESS',
    UPDATE_PRODUCER_FAIL: 'UPDATE_PRODUCER_FAIL',
    RESET_PRODUCER: 'RESET_PRODUCER',
    ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
    ADD_ITEM_FAIL: 'ADD_ITEM_FAIL',
    UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
    UPDATE_ITEM_FAIL: 'UPDATE_ITEM_FAIL',
    RESET_ITEM: 'RESET_ITEM',
    SHOP_SET_PAGE: 'SHOP_SET_PAGE',
    SHOP_SET_TOTAL_PAGE: 'SHOP_SET_TOTAL_PAGE',
    CATEGORY_SET_PAGE: 'CATEGORY_SET_PAGE',
    CATEGORY_SET_TOTAL_PAGE: 'CATEGORY_SET_TOTAL_PAGE',
    PRODUCER_SET_PAGE: 'PRODUCER_SET_PAGE',
    PRODUCER_SET_TOTAL_PAGE: 'PRODUCER_SET_TOTAL_PAGE',
    BILL_SET_PAGE: 'BILL_SET_PAGE',
    BILL_SET_TOTAL_PAGE: 'BILL_SET_TOTAL_PAGE',
    BILL_SET_DATA: "BILL_SET_DATA",
    
    UPDATE_ISSEND_SUCCESS: 'UPDATE_ISSEND_SUCCESS',
    UPDATE_ISSEND_FAIL: 'UPDATE_ISSEND_FAIL',
}

export const userTypes = {
    SET_USER: 'SET_USER',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAIL: 'ADD_USER_FAIL',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
    RESET_USER: 'RESET_USER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_PAGE:'SET_TOTAL_PAGE'
}

export const homeTypes = {
    SET_TOP_PRODUCT:' SET_TOP_PRODUCT'
}